# Site
url: https://aideepgeek.github.io/
name: "AI Daily by DeepGeekAI"
title: "AI Daily by DeepGeekAI"
description: "每天为您精选全球科技巨头动态、行业创新趋势与深度观点剖析，助您洞察 AI 发展脉络，掌握未来科技方向。"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /ai-daily
google_analytics: 'UA-46278016-1'
disqus: 'ibillxia'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
#permalink: /:title/
permalink: /:year/:month/:title/


# Authors
authors:
  sal:
    name: DeepGeekAI
    display_name: DeepGeekAI
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: aideepgeek@gmail.com
    web: https://aideepgeek.github.io
    twitter: https://x.com/aideepgeek
    description: "DeepGeek.AI"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "pub-5786957483481554"
adsense-data-ad-slot: "5029197189"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
# Disqus Comments
disqus_short_name: ibillxia
disqus_show_comment_count: true